routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/category/{slug?}', 'ShopController@category')->name('category');
Route::get('/product/{slug?}', 'ShopController@products')->name('product');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::group(['prefix'=> '/', 'middleware' => 'role:admin'],function (){
        Route::get('/', 'DashboardController@dashboard')->name('admin.index');
        Route::resource('/category', 'CategoryController', ['as'=>'admin']);
        Route::resource('/product', 'ProductController', ['as'=>'admin']);
        Route::resource('/price', 'PriceController', ['as'=>'admin']);
        Route::group(['prefix'=> 'user_management', 'namespace' => 'UserManagement'], function () {
            Route::resource('/users', 'UserController', ['as' => 'admin.user_management']);
        });

    });

});


Route::get('/', function () {
    return view('front.home');
});

Auth::routes();


Route::get('/public/uploads/{filename}', function ($filename)
{
    $path = public_path('/uploads/' . $filename);


    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});



Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="jumbotron text-center display-3">
                    <p><span class="badge badge-primary ">Категорий {{$count_categories}}</span></p>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="jumbotron text-center display-3">
                    <p><span class="badge badge-primary ">Товаров {{$count_products}}</span></p>
                </div>
            </div>


        </div>

        <div class="col-sm-6 float-left">
                <a href="{{route('admin.category.create')}}" class="btn btn-block btn-default">Создать категорию</a>
                @foreach($categories as $category)
                    <div class="container list-group-item">
                        <div class="row">
                            <div class="col-sm-10 ">
                                <h4 class="list-group-item-heading">{{$category->title}}</h4>
                                <p class="list-group-item-text">{{$category->products()->count()}}</p>
                            </div>
                            <div class="col-sm-2 ">
                                <a class="btn-info btn"  href="{{route('admin.category.edit', $category)}}" >
                                    <i class="fa fa-edit"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    @endforeach()

        </div>
        <div class="col-sm-6 float-right">
                <a href="{{route('admin.product.create')}}" class="btn btn-block btn-default">Создать товар</a>
                    @foreach($products as $product)
                        <div class="container list-group-item">
                            <div class="row">
                                <div class="col-sm-10 ">
                                    <h4 class="list-group-item-heading">{{$product->title}}</h4>
                                    <p class="list-group-item-text">
                                        {{$product->categories()->pluck('title')->implode(', ')}}
                                    </p>
                                </div>
                                <div class="col-sm-2 ">
                                    <a class="btn-info btn"  href="{{route('admin.product.edit', $product)}}" >
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </div>
                            </div>
                        </div>

                        @endforeach

            </div>
        </div>
    </div>

@endsection