routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/category/{slug?}', 'ShopController@category')->name('category');
Route::get('/product/{slug?}', 'ShopController@products')->name('product');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth'] ], function () {
    Route::group(['prefix'=> '/', 'middleware' => 'role:admin'],function (){
        Route::get('/', 'DashboardController@dashboard')->name('admin.index');
        Route::resource('/category', 'CategoryController', ['as'=>'admin']);
        Route::resource('/product', 'ProductController', ['as'=>'admin']);
        Route::resource('/price', 'PriceController', ['as'=>'admin']);
        Route::group(['prefix'=> 'user_management', 'namespace' => 'UserManagement'], function () {
            Route::resource('/users', 'UserController', ['as' => 'admin.user_management']);
        });

    });

});


Route::get('/', function () {
    return view('front.home');
});

Auth::routes();


Route::get('/public/uploads/{filename}', function ($filename)
{
    $path = public_path('/uploads/' . $filename);


    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});



Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Models\Roles','user_roles','user_id','role_id');
    }

    /**
     *
     * @return boolean
     */
    public function isEmployee(){
        $roles = $this->roles->toArray();
        return !empty($roles);
    }

    /**
     * @return boolean
     */
    public function hasRole($check){
        return in_array($check, array_pluck($this->roles->toArray(), 'name'));
    }

    /**
     * @return int
     */
    private function getIdInArray($array, $term)
    {
        foreach ($array as $key => $value){
            if($value == $term){
                return $key+1;
            }
        }
        return false;
    }

    /**
     * @return boolean
     */
    public function makeEmployee($title)
    {
        $assinged_roles = array();
        $roles = array_feth(Roles::all()->toArray(), 'name');
        switch ($title){
            case 'admin' :
                $assinged_roles[ ] = $this->getIdInArray($roles, 'admin');
            case 'client' :
                $assinged_roles[ ] = $this->getIdInArray($roles, 'client');
                break;
            default:
                $assinged_roles[ ] = false;

        }
        $this->roles()->attach($assinged_roles);
    }
}

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user_management.users.index', [
            'users' => User::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_management.users.create', [
            'user' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password'])
        ]);
        return redirect()->route('admin.user_management.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user_management.users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id)
            ],
            'password' => 'nullable|string|min:6|confirmed',
        ]);
        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] = null ?: $user->password = bcrypt($request['password']);
        $user->save();

        return redirect()->route('admin.user_management.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.user_management.users.index');
    }
}

resources/views/admin/user_management/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Создание пользователя @endslot
            @slot('parent') Главная @endslot
            @slot('active') Пользователи @endslot
        @endcomponent
        <hr>
        <form class="form-horizontal" action="{{route('admin.user_management.users.store')}}" method="post">

            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.user_management.users.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/user_management/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Редактирование пользователя @endslot
            @slot('parent') Главная @endslot
            @slot('active') Пользователи @endslot
        @endcomponent
        <hr>
        <form class="form-horizontal" action="{{route('admin.user_management.users.update', $user)}}" method="post">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.user_management.users.partials.form')
        </form>
    </div>
@endsection

resources/views/admin/user_management/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('title') Список пользователей @endslot
            @slot('parent') Главная @endslot
            @slot('active') Пользователи @endslot

        @endcomponent

        <hr>
        <a href="{{route('admin.user_management.users.create')}}" class="btn btn-primary float-right"><i
                    class="fa fa-plus-square-o"></i> Создать пользователя</a>
        <table class="table table-striped">
            <thead>
            <th>Имя</th>
            <th>Email</th>
            <th class="text-right">Действие</th>
            </thead>
            <tbody>
            @forelse($users as $user)
                <tr>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td class="text-right">

                        <form onsubmit="if(confirm('Удалить')){ return true;}else{ return false}"
                              action="{{route('admin.user_management.users.destroy', $user)}}" method="post">
                            {{method_field('DELETE')}}

                            <a href="{{route('admin.user_management.users.edit', $user)}}" class="btn btn-info">
                                <i class="fa fa-edit"></i>
                            </a>

                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center">
                        <h2>Данные отсутствуют</h2>
                    </td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="3">
                    <ul class="pagination pull-right">
                        {{ $users->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection